#!/bin/bash

if [ $USER != "root" ]; then
#        echo 'script must be run sudo'
#        exit
	echo "info: starting as normal used (startin as root seems not a brilliant idea)"
	echo "      hope that this won't break anything"
fi

pkill node

node bin/jsgamebench -8081 >& logs/jsgamebench.log &
